language: node_js
node_js:
  - '10.4.1'
before_script:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
